<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RegistrationRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>'required|max:255',
            'email'=>'required',
            'dept'=>'required',
        ];
    }

    public function messages()
    {
        return [
            'name.required'=>"Name Cannot be empty",
            'email.required'=>"Email Cannot be empty",
            'dept.required'=>"Department Cannot be empty",
        ]; // TODO: Change the autogenerated stub
    }
}
